CREATE DATABASE mydb;

USE mydb;

CREATE TABLE DEPARTMENT (
    DNUMBER INT PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL,
    MGRSSN CHAR(9),
    MGRSTARTDATE DATE
);


CREATE TABLE EMPLOYEE (
    SSN CHAR(9) PRIMARY KEY,
    FNAME VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30) NOT NULL,
    BDATE DATE,
    ADDRESS VARCHAR(100),
    SEX CHAR(1),
    SALARY DECIMAL(10,2),
    SUPERSSN CHAR(9),
    DNO INT
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_DEPT
FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMP_SUPER
FOREIGN KEY (SUPERSSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPT_MGR
FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN);

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT,
    DLOCATION VARCHAR(50),
    PRIMARY KEY (DNUMBER, DLOCATION),
    FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE PROJECT (
    PNUMBER INT PRIMARY KEY,
    PNAME VARCHAR(50) NOT NULL,
    PLOCATION VARCHAR(50),
    DNUM INT,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE WORKS_ON (
    ESSN CHAR(9),
    PNO INT,
    HOURS DECIMAL(4,1),
    PRIMARY KEY (ESSN, PNO),
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER)
);

CREATE TABLE DEPENDENT (
    ESSN CHAR(9),
    DEPENDENT_NAME VARCHAR(50),
    SEX CHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(30),
    PRIMARY KEY (ESSN, DEPENDENT_NAME),
    FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN)
);




